# Week 2 - Monday Lesson (variable assignment, loops, lists)

## Tasks Today:

1) Int & Float assignments <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Assigning int <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Assigning float <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Performing Calculations on ints and floats <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Addition <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Subtraction <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Floor Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Modulo <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Exponential <br>
2) String Input-Output <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) String Assignment <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) print() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) String Concatenation <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Type Conversion <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) input() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) format() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Old Way (python 2) <br>
3) <b>In-Class Exercise #1</b> <br>
4) If Statements <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) 'is' keyword <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) 'in' keyword <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) 'not in' keyword <br>
5) <b>In-Class Exercise #2</b> <br>
6) Elif Statements <br>
7) Else Statements <br>
8) <b>In-Class Exercise #3</b> <br>
9) For Loops <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Using 'in' keyword <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Continue Statement <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Break Statement <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Pass Statement <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Double For Loops <br>
10) While Loops <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Looping 'While True' <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) While and For Loops Used Together <br>
11) Built-In Functions <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) range() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) len() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) help() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) isinstance() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) abs() <br>
12) Try and Except <br>
13) Lists <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Declaring Lists <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Indexing a List <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) .append() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) .insert() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) .pop() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) .remove() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) del() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Concatenating Two Lists <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Lists Within Lists <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Looping Through Lists <br>

### Int & Float Assignments

##### Assigning int

In [1]:
number = 6

print(number)

6

##### Assinging float

In [4]:
numberFloat = 2.3
print(numberFloat)
print(numberFloat)
numberFloat = 7.2
print(numberFloat)

2.3
2.3
7.2

#### Performing Calculations on ints and floats

##### Addition

In [6]:
num1 = 2
num2 = 5.4

result = num1 + num2

print(result)

result += 2
print(result)

7.4
9.4

##### Subtraction

In [8]:
result_diff = num2 - num1
print(result_diff)

result_diff -= 1
print(result_diff - 1)

3.4000000000000004
2.4000000000000004

##### Multiplication

In [10]:
result_mul = num1 * num2
print(result_mul)

result_mul *= 2
print(result_mul)

10.8
21.6

##### Division

In [14]:
result_div = num2/num1
print(result_div)

result_div /= 3
print(result_div)

2.7
0.9

##### Floor Division

In [16]:
result_floor = num2 // num1
print(result_floor)

result_floor //= 2
print(result_floor)

2.0
1.0

##### Modulo

In [20]:
result_mod = 13 % 2
print(result_mod)

result_mod %= 2
print(result_mod)

1
1

##### Exponential

In [22]:
square = 5 ** 2
print(square)

square **= 2
print(square)

25
625

### String Input-Output

##### String Assignment

In [25]:
name = "Brittany"
print(name)

Brittany

##### print() <br>
<p>Don't forget about end=' '</p>

In [29]:
print("This is my first name:", name)

print("Full Name:", name , end=" Farrell")

This is my first name: Brittany
Full Name: Brittany Farrell

##### String Concatenation

In [34]:
first_name = "John"
last_name = "Smith"

full_name = first_name + " " + last_name
print(full_name)

full_name += ", Jr"
print(full_name)

John Smith
John Smith, Jr

##### Type Conversion

In [36]:
number = "32"

change_type_num = int(number)
print(number)
print(change_type_num +1)

32
33

##### input()

In [ ]:
#Input will always return a string

# name = input('What is your name?')
# print('Nice to meet you,' + name)

age = int(input('What is your age?: ')
add_age = age + 5
print(add_age)

##### format()

In [41]:
age = input('What is your age? ')

result_string = 'You are {} {} and you are getting wiser!'.format(age, name)
print(result_string)

result_again = f"{age} is a great time in life!"
print(result_again)

What is your age? 25
You are 25 Brittany and you are getting wiser!
25 is a great time in life!

##### Old Way (python 2)

In [42]:
result_string2 = "You are %s and you look great for your age!" %age
print(result_string2)

You are 25 and you look great for your age!

# In-Class Exercise 1 <br>
<p>Create a format statement that asks for color, year, make, model and prints out the results</p>

In [51]:
color = input('What is your favorite color? ')
color_response = (color , 'is a cool color! ')
print(color_response)

year = input('What is year is it? ')
year_response = (year, 'is going to be a great year!')
print(year_response)

make_model = input('What is the make and model of your car?')
make_model_response = ( "Your " + make_model + " is in good condition.")
print(make_model_response)

What is your favorite color? blue
('blue', 'is a cool color! ')
What is year is it? 2023
('2023', 'is going to be a great year!')
What is the make and model of your car?mercedes ala 250
Your mercedes ala 250 is in good condition.

### If Statements

In [65]:
# Available operators: Greater(>), Less(<),Equal(==)
# Greater or Equal(>=), Less or Equal (<=)

# Truth Tree:
# T && F = F
# T && T = T
# T || F = T
# F || T = T
# F || F = F

num1 = 5
num2 = 10
num3 = 0

# if num1 == num2:
#     print('Equal Values!')
    
# else:
#     print('Not Equal!')

if num2 < num1 or num3 > 0:
    print("Num2 is greater")
elif num1 > num2:
    print("Num1 is greater")
else:
    print("Equal Values")

Equal Values

##### 'is' keyword

In [67]:
# The "is" keyword is for checking the same object, but not the same value

num3 = 55

if num3 == 55:
    print("This is the exact number/object")

This is the exact number/object

##### 'in' keyword

In [69]:
# Check is a character is in a string

char_name = "Frodo Baggins"

if "Frodo" in char_name:
    print("The ring bearer")

The ring bearer

##### 'not in' keyword'

In [70]:
saga_char = "Sonic"

if 'a' not in saga_char:
    print( 'a is NOT here...')

a is NOT here...

# In-Class Exercise 2 <br>
<p>Ask user for input, check to see if the letter 'p' is in the input</p>

In [73]:
# OUTPUT: True -- if p is found
# False -- if p is NOT found

nintendo_char = "Princess Peach"

if 'p' in nintendo_char:
    print( "The letter 'p' is here!")

## Using 'and'/'or' with If Statements

In [77]:
num_11 = 15
num_12 = 3
num_13 = 13
num_14 = 3

#if with 'and'statement
if num_11 / 5 == num_12 and num_13 - 7 == num_14:
    print("True and True")
    
# if with 'or'statement
if num_13 == num_14 or num_11 > num_12:
    print("False and True")

False and True

### Elif Statements

In [79]:
first_name = input('What is your name? ')

if first_name == 'Smith':
    print("The name is Smith. ")
elif first_name == 'Brittany':
    print("The name is Brittany ")
elif first_name != 'Max':
    print("The name is NOT Max ")
else:
    print("The name is Max")

What is your name? Brittany
The name is Brittany

### Else Statements

In [ ]:
# see above

### For Loops

In [82]:
#Syntax:
#for counter in condition

name = "Brittany" 

for letter in name:
    print(name)

Brittany
Brittany
Brittany
Brittany
Brittany
Brittany
Brittany
Brittany

##### Using 'in' keyword

In [ ]:
# see above

##### Continue Statement

In [ ]:
# will continue to next iteration

In [84]:
for i in range(20):
    if i == 5:
        continue
    print(i)

0
1
2
3
4
6
7
8
9
10
11
12
13
14
15
16
17
18
19

##### Break Statement

In [ ]:
# will break out of current loop

In [88]:
for i in range(20):
    if i == 5:
        break
        print(i)

##### Pass Statement

In [ ]:
# mostly used as a placeholder, and will continue on same iteration

In [89]:
name = "Brittany"

for i in name:
    pass

##### Double For Loops

In [90]:
for i in range(5):
    for j in range(5):
        print('i = ' , i , 'j = ' , j)

i =  0 j =  0
i =  0 j =  1
i =  0 j =  2
i =  0 j =  3
i =  0 j =  4
i =  1 j =  0
i =  1 j =  1
i =  1 j =  2
i =  1 j =  3
i =  1 j =  4
i =  2 j =  0
i =  2 j =  1
i =  2 j =  2
i =  2 j =  3
i =  2 j =  4
i =  3 j =  0
i =  3 j =  1
i =  3 j =  2
i =  3 j =  3
i =  3 j =  4
i =  4 j =  0
i =  4 j =  1
i =  4 j =  2
i =  4 j =  3
i =  4 j =  4

### While Loops

In [91]:
#Syntax:
#while keyword,condition statement

num = 0

while num < 10:
    print(num)
    num += 1

0
1
2
3
4
5
6
7
8
9

##### Looping 'While True'

In [92]:
game_over = True

while game_over:
    print("Infinite Loop")
    if game_over == False:
        break

Infinite Loop

##### While & For Loops Used Together

In [ ]:
num = 0

while num < 5:
    print("\n While loop iteration: " + str(num))
    
    for i in range (2):
        print("For loop iteration: ", str(i))
        
    num += 1

### Built-In Functions

##### range()

In [99]:
#range(start, stop, step)

for i in range(2, 20, 3):
    print(i)

2
5
8
11
14
17

##### len()

In [101]:
name = input("What is the name of your favorite book? ")

length = len(name)
print(length)

What is the name of your favorite book? Harry Potter
12

##### help()

In [ ]:
#Use this function to view more information on python functions

##### isinstance()

In [102]:
#Check a variable to find out what object family or data type it belongs to
#isinstance (var, type)

num = 4.5
if isinstance(num, int):
    print(f"{num} is an int!")
else:
    print(f"{num} is a float!")

4.5 is a float!

##### abs()

In [103]:
#(-5) = 5

print(abs(-5))

5

### Try and Except

In [107]:
# Use this to log out graceful and useful error messages
# Does not stop the program!

try:
    input_num = int(input("Guess a number"))
    print('Your number is ' + str(input_num))
except:
    print("That didn't work! Change your input to a number.")

Guess a number5
Your number is 5

### Lists

##### Declaring Lists

In [116]:
list_1 = []

names =('Max', 'Cindy', 'Faith', 'bob','Nate' )
print(names)

('Max', 'Cindy', 'Faith', 'bob', 'Nate')

##### Indexing a List

In [135]:
#list name(start, stop, step)

#single index
print(names[0])

#Print starting at index 1 going to end
print(names[1:])

#Print starting at the beginning of a list up until a number
print(names[:2])

#Print starting at index 1 and going up by 2 in each iteration
print(names[1::2])

#Print starting at the back and present in reverse order
print(names[::-1])

Max
('Cindy', 'Faith', 'bob', 'Nate')
('Max', 'Cindy')
('Cindy', 'bob')
('Nate', 'bob', 'Faith', 'Cindy', 'Max')

##### .append()

In [122]:
names.append('Brittany')
print(names)

AttributeError: 'tuple' object has no attribute 'append'

##### .insert()

In [ ]:
names.insert(1, 'Darrell')
print(names)

##### .pop()

In [136]:
#Default to the last value if to parameter is given 
#Pop returns the element that was removed in case you want to assign it to a variable

my_name = names.pop[2]
print(my_name)
print(names)

AttributeError: 'tuple' object has no attribute 'pop'


##### .remove()

In [ ]:
#Value to be removed rather than index
# names.remove('bob')
# print(names)

#remove multiple brittanys from list
while 'Brittany' in names:
    names.remove('Brittany')
    print(names)

##### del()

In [ ]:
#Goes by index rather than value
#Be careful with del. it can cause index errors if not used carefully

del(names[1])
print(names)

##### Concatenating Two Lists

In [137]:
#Will append two lists together, will NOT add the values!

list_2 = [0, 1, 2]
list_3 = [3, 4, 5]

large_list = list_2 + list_3
print(large_list)

[0, 1, 2, 3, 4, 5]

##### Lists Within Lists

In [138]:
#Lists can hold any other type of element, including other lists
#They can go as deep as you want. This is called nested lists

names = ['Max', 'Sam', 'Josh',['Sally',['Sue', 'Jim'], 'Tamika']]
print(names)
print(names[3][1][1])

['Max', 'Sam', 'Josh', ['Sally', ['Sue', 'Jim'], 'Tamika']]
Jim

##### Looping Through Lists

In [140]:
#Two ways to loop through lists: One is by index; other by using 'in' keyword

#By index
for i in range(len(names)):
    print(names[i])

#loop with 'in'
for i in names:
    print(i)

## Exercise #1 <br>
<p>Cube Number Test... Print out all cubed numbers up to the total value 1000. Meaning that if the cubed number is over 1000 break the loop.</p>

In [114]:
for i in range (1,1000):
    print(i **3)
for i in range (1,1000):
    if i == 1000:
        break
        print(i)

1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744
3375
4096
4913
5832
6859
8000
9261
10648
12167
13824
15625
17576
19683
21952
24389
27000
29791
32768
35937
39304
42875
46656
50653
54872
59319
64000
68921
74088
79507
85184
91125
97336
103823
110592
117649
125000
132651
140608
148877
157464
166375
175616
185193
195112
205379
216000
226981
238328
250047
262144
274625
287496
300763
314432
328509
343000
357911
373248
389017
405224
421875
438976
456533
474552
493039
512000
531441
551368
571787
592704
614125
636056
658503
681472
704969
729000
753571
778688
804357
830584
857375
884736
912673
941192
970299
1000000
1030301
1061208
1092727
1124864
1157625
1191016
1225043
1259712
1295029
1331000
1367631
1404928
1442897
1481544
1520875
1560896
1601613
1643032
1685159
1728000
1771561
1815848
1860867
1906624
1953125
2000376
2048383
2097152
2146689
2197000
2248091
2299968
2352637
2406104
2460375
2515456
2571353
2628072
2685619
2744000
2803221
2863288
2924207
2985984
3048625
3112136
3176523
3241792
3307949
3375000
3442951
3511808
3581577
3652264
3723875
3796416
3869893
3944312
4019679
4096000
4173281
4251528
4330747
4410944
4492125
4574296
4657463
4741632
4826809
4913000
5000211
5088448
5177717
5268024
5359375
5451776
5545233
5639752
5735339
5832000
5929741
6028568
6128487
6229504
6331625
6434856
6539203
6644672
6751269
6859000
6967871
7077888
7189057
7301384
7414875
7529536
7645373
7762392
7880599
8000000
8120601
8242408
8365427
8489664
8615125
8741816
8869743
8998912
9129329
9261000
9393931
9528128
9663597
9800344
9938375
10077696
10218313
10360232
10503459
10648000
10793861
10941048
11089567
11239424
11390625
11543176
11697083
11852352
12008989
12167000
12326391
12487168
12649337
12812904
12977875
13144256
13312053
13481272
13651919
13824000
13997521
14172488
14348907
14526784
14706125
14886936
15069223
15252992
15438249
15625000
15813251
16003008
16194277
16387064
16581375
16777216
16974593
17173512
17373979
17576000
17779581
17984728
18191447
18399744
18609625
18821096
19034163
19248832
19465109
19683000
19902511
20123648
20346417
20570824
20796875
21024576
21253933
21484952
21717639
21952000
22188041
22425768
22665187
22906304
23149125
23393656
23639903
23887872
24137569
24389000
24642171
24897088
25153757
25412184
25672375
25934336
26198073
26463592
26730899
27000000
27270901
27543608
27818127
28094464
28372625
28652616
28934443
29218112
29503629
29791000
30080231
30371328
30664297
30959144
31255875
31554496
31855013
32157432
32461759
32768000
33076161
33386248
33698267
34012224
34328125
34645976
34965783
35287552
35611289
35937000
36264691
36594368
36926037
37259704
37595375
37933056
38272753
38614472
38958219
39304000
39651821
40001688
40353607
40707584
41063625
41421736
41781923
42144192
42508549
42875000
43243551
43614208
43986977
44361864
44738875
45118016
45499293
45882712
46268279
46656000
47045881
47437928
47832147
48228544
48627125
49027896
49430863
49836032
50243409
50653000
51064811
51478848
51895117
52313624
52734375
53157376
53582633
54010152
54439939
54872000
55306341
55742968
56181887
56623104
57066625
57512456
57960603
58411072
58863869
59319000
59776471
60236288
60698457
61162984
61629875
62099136
62570773
63044792
63521199
64000000
64481201
64964808
65450827
65939264
66430125
66923416
67419143
67917312
68417929
68921000
69426531
69934528
70444997
70957944
71473375
71991296
72511713
73034632
73560059
74088000
74618461
75151448
75686967
76225024
76765625
77308776
77854483
78402752
78953589
79507000
80062991
80621568
81182737
81746504
82312875
82881856
83453453
84027672
84604519
85184000
85766121
86350888
86938307
87528384
88121125
88716536
89314623
89915392
90518849
91125000
91733851
92345408
92959677
93576664
94196375
94818816
95443993
96071912
96702579
97336000
97972181
98611128
99252847
99897344
100544625
101194696
101847563
102503232
103161709
103823000
104487111
105154048
105823817
106496424
107171875
107850176
108531333
109215352
109902239
110592000
111284641
111980168
112678587
113379904
114084125
114791256
115501303
116214272
116930169
117649000
118370771
119095488
119823157
120553784
121287375
122023936
122763473
123505992
124251499
125000000
125751501
126506008
127263527
128024064
128787625
129554216
130323843
131096512
131872229
132651000
133432831
134217728
135005697
135796744
136590875
137388096
138188413
138991832
139798359
140608000
141420761
142236648
143055667
143877824
144703125
145531576
146363183
147197952
148035889
148877000
149721291
150568768
151419437
152273304
153130375
153990656
154854153
155720872
156590819
157464000
158340421
159220088
160103007
160989184
161878625
162771336
163667323
164566592
165469149
166375000
167284151
168196608
169112377
170031464
170953875
171879616
172808693
173741112
174676879
175616000
176558481
177504328
178453547
179406144
180362125
181321496
182284263
183250432
184220009
185193000
186169411
187149248
188132517
189119224
190109375
191102976
192100033
193100552
194104539
195112000
196122941
197137368
198155287
199176704
200201625
201230056
202262003
203297472
204336469
205379000
206425071
207474688
208527857
209584584
210644875
211708736
212776173
213847192
214921799
216000000
217081801
218167208
219256227
220348864
221445125
222545016
223648543
224755712
225866529
226981000
228099131
229220928
230346397
231475544
232608375
233744896
234885113
236029032
237176659
238328000
239483061
240641848
241804367
242970624
244140625
245314376
246491883
247673152
248858189
250047000
251239591
252435968
253636137
254840104
256047875
257259456
258474853
259694072
260917119
262144000
263374721
264609288
265847707
267089984
268336125
269586136
270840023
272097792
273359449
274625000
275894451
277167808
278445077
279726264
281011375
282300416
283593393
284890312
286191179
287496000
288804781
290117528
291434247
292754944
294079625
295408296
296740963
298077632
299418309
300763000
302111711
303464448
304821217
306182024
307546875
308915776
310288733
311665752
313046839
314432000
315821241
317214568
318611987
320013504
321419125
322828856
324242703
325660672
327082769
328509000
329939371
331373888
332812557
334255384
335702375
337153536
338608873
340068392
341532099
343000000
344472101
345948408
347428927
348913664
350402625
351895816
353393243
354894912
356400829
357911000
359425431
360944128
362467097
363994344
365525875
367061696
368601813
370146232
371694959
373248000
374805361
376367048
377933067
379503424
381078125
382657176
384240583
385828352
387420489
389017000
390617891
392223168
393832837
395446904
397065375
398688256
400315553
401947272
403583419
405224000
406869021
408518488
410172407
411830784
413493625
415160936
416832723
418508992
420189749
421875000
423564751
425259008
426957777
428661064
430368875
432081216
433798093
435519512
437245479
438976000
440711081
442450728
444194947
445943744
447697125
449455096
451217663
452984832
454756609
456533000
458314011
460099648
461889917
463684824
465484375
467288576
469097433
470910952
472729139
474552000
476379541
478211768
480048687
481890304
483736625
485587656
487443403
489303872
491169069
493039000
494913671
496793088
498677257
500566184
502459875
504358336
506261573
508169592
510082399
512000000
513922401
515849608
517781627
519718464
521660125
523606616
525557943
527514112
529475129
531441000
533411731
535387328
537367797
539353144
541343375
543338496
545338513
547343432
549353259
551368000
553387661
555412248
557441767
559476224
561515625
563559976
565609283
567663552
569722789
571787000
573856191
575930368
578009537
580093704
582182875
584277056
586376253
588480472
590589719
592704000
594823321
596947688
599077107
601211584
603351125
605495736
607645423
609800192
611960049
614125000
616295051
618470208
620650477
622835864
625026375
627222016
629422793
631628712
633839779
636056000
638277381
640503928
642735647
644972544
647214625
649461896
651714363
653972032
656234909
658503000
660776311
663054848
665338617
667627624
669921875
672221376
674526133
676836152
679151439
681472000
683797841
686128968
688465387
690807104
693154125
695506456
697864103
700227072
702595369
704969000
707347971
709732288
712121957
714516984
716917375
719323136
721734273
724150792
726572699
729000000
731432701
733870808
736314327
738763264
741217625
743677416
746142643
748613312
751089429
753571000
756058031
758550528
761048497
763551944
766060875
768575296
771095213
773620632
776151559
778688000
781229961
783777448
786330467
788889024
791453125
794022776
796597983
799178752
801765089
804357000
806954491
809557568
812166237
814780504
817400375
820025856
822656953
825293672
827936019
830584000
833237621
835896888
838561807
841232384
843908625
846590536
849278123
851971392
854670349
857375000
860085351
862801408
865523177
868250664
870983875
873722816
876467493
879217912
881974079
884736000
887503681
890277128
893056347
895841344
898632125
901428696
904231063
907039232
909853209
912673000
915498611
918330048
921167317
924010424
926859375
929714176
932574833
935441352
938313739
941192000
944076141
946966168
949862087
952763904
955671625
958585256
961504803
964430272
967361669
970299000
973242271
976191488
979146657
982107784
985074875
988047936
991026973
994011992
997002999
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999

## Exercise #2 <br>
<p>Get first prime numbers up to 100</p>

In [133]:
# HINT::
# An else after an if runs if the if didn’t
# An else after a for runs if the for didn’t break

#I seeked help on if with modulo portion but got confused from the 'for'j in range...
for i in range(2, 101):
    if i > 1:
        for j in range(2, i):
            if (i % j) == 0:
                print(i, "no")
            break
        else:
            print(i, "yay")

SyntaxError: invalid syntax (1802763549.py, line 9)

# Exercise 3 <br>
<p>Take in a users input for their age, if they are younger than 18 print kids, if they're 18 to 65 print adults, else print seniors</p>

In [132]:
age = int(input('Please enter a persons age.'))

if age <= 18:
    print('This person is a kid! ')
elif age > 18 and age < 65:
    print('This person is an adult! ')
elif age > 65:
    print('This person is a senior! ')
else:
    print('This person is not a person. ')

Please enter a persons age.15
This person is a kid!